# Preliminary Content {-}

## Acknowledgements {-}

I would like to begin by thanking my professors, Professor Colin Rundel, Professor Christopher Timmins and Professor Grace Kim. Thank you to Professor Rundel for your wisdom and patience. I did not realize that pursuing research was not only an academic pursuit but also a huge emotional undertaking, and your insight and calming presence was so critical in this process. Thank you for listening to every idea I had with an open-mind, and walking with me through the detailed processes necessary to get answers to each of these curiosities. Thank you to Professor Timmins for your support and guidance at all hours of the day, and for constantly challenging me to think critically about the questions I was asking and the methodology I was using. It was a pleasure working with you this year, and I learned so much from you. Thank you also to Professor Grace Kim for your feedback and your constant support of my winding research path, as well as of my career throughout Duke. Finally, thank you to Professor Amy Herring and Jim Clarke for serving on my committee.
Thank you to John Killeen at DataWorks. Without your trust in me to pursue this research question with the care it deserves, this research would not have been possible. Thank you for all of the brainstorming sessions and hours spent investigating imperfect data problems. I learned so much through your mentorship. 
Thank you to the Durham Sherriff’s Department and Durham Tax Administration for letting me work with this data in my thesis. Finally, thank you to all of the friends who have kept me sane as I panicked about this research project: Anna-Karin Hess, David Pfeiffer, and Juan Philippe, I could not have done this without your support! 


## Preface {-}

This is an example of a thesis setup to use the reed thesis document class
(for LaTeX) and the R bookdown package, in general.

## Dedication {-}

You can have a dedication here if you wish. 

`r if(!knitr:::is_latex_output()) '## Abstract {-}'`
