# Discussion of Results and Further Research

Overall, I find that the proportion of multi-family dwellings owned by institutional investors have increased in Durham across all property sizes since 2000, which is consistent with the current literature. I also find that amongst corporate owners, specifically, the proportion of owners based out-of-state has increased. Evidently, corporate and out-of-state landlords are becoming the dominant owners of multi-family rental complexes in Durham. 
Understanding the changes in the ownership make-up of Durham’s multi-family rental market is an important contribution of my thesis. No previous work has attempted to understand how the players in the real-estate market are changing at the corporate and individual level or considered the owner’s location to be significant. My thesis presents evidence of a marked trend across different property sizes. Using the methodology outlined in this paper, I would recommend that future research attempts to conduct similar analyses to understand the structural changes across our nation’s real-estate markets. I also recommend that in research conducted on the multi-family sector, different property sizes be analyzed differently, since trends in both ownership and eviction rates vary significantly across property sizes.  

In my research, I find that corporates are less likely to evict than individual landlords are. This finding goes against initial expectations and suggests that individual landlords are more intimately tied to housing instability. However, as discussed in the Literature Review, eviction filings are only one factor that may lead to a tenant’s displacement. There are countless examples of corporations utilizing tactics such as rent hikes and deteriorating living conditions in other rental markets (Abood, 2018; Fields, 2015). On the flip side, informal evictions, such as forcing a tenant to leave through brute force with no legal justification, may be prevalent among individual landlords (Desmond, 2017). Thus, it is impossible to make any definitive conclusions relating landlord type to housing instability through this research alone. Still, this research does suggest that in smaller property sizes, individuals utilize eviction filings at higher rates, while in the largest property size, corporates tend to file evictions at higher rates.  

I also find that overall, investors based out-of-state are less likely to evict than in-state owners are. This suggests that the phenomenon of the distanced investor [^6] as discussed in my Literature Review may not necessarily be relevant to Durham. We cannot definitively say that individuals and local corporate owners contribute more or less to housing instability, but we can consider potential reasons that explain differences in eviction filing rates. One reason may be that in the Durham rental market, the livelihoods of individual owners and local corporates are more directly tied to the rental income from their tenants. Thus, these landlords may not have the flexibility and band-with that larger landlords do.  

Yet, I also find that investors who own more than 15 multi-family properties in Durham, which I consider to be “large” investors, are more likely to evict tenants than smaller investors are when considering both corporate landlords and individuals. The explanation that larger investors are more flexible, and therefore evict at lower rates, is not quite adequate. This finding suggests that perhaps, we must pay more attention to consolidation by a few landlords no matter what type of entity they are, as landlords with a larger consolidation of units seem to be more likely to evict. This finding is consistent with the finding by Raymond et. al in their 2016 case study on Atlanta that larger investors in the single-family rental market, defined as investors that hold more than 15 single-family rental units, evict at higher rates (Raymond et. al, 2016).  

One limitation of my thesis is that it does not consider other potentially important predictors that would give idiosyncratic insight at the property-level. For example, it would be helpful to have information on rents across these units. Unfortunately, this data was not possible to retrieve for the purposes of this research. Similarly, property taxes or improvement values would be another important variable in understanding potential landlord behavior and motivation. In future research, looking at building permits or other property value assessments may yield important insight into investor strategy, which could be analyzed quantitatively using Mallach’s framework (Mallach, 2010).  

There is much more work to be done to understand the true causes of housing instability in Durham County. As property values and rents continue to rise, the types of residents who can afford to live in the city of Durham will change. Poorer residents who can no longer afford the rising rents will have to move. This type of phenomenon exists outside the confines of formal eviction processes but is just as significant in the creation of housing instability.  

This research should be extended to other communities to understand changes in other real-estate markets. Most importantly, similar analyses between the relationship of landlords and housing instability should be conducted in other areas with high rates of displacement. Moving forward, researchers must think creatively about potential proxies to measure displacement. More qualitative investigation may be helpful into factors such as the living conditions of properties under different types of ownership. Finally, more nuanced research must be conducted to determine whether certain biases exist in the rental space that lead to the higher eviction rates amongst low-income and minority groups.

[^6]: The distanced investor is a case where it is not completely clear who the landlord is, and tenants perceive some difficulty in reaching their landlord to discuss their personal situation.
