# Conclusion {-}

For better or for worse, our landlords are changing. More institutional owners are buying rental properties and taking share away from many of the small investors with small inventories that used to represent the hallmark landlord. At the same time, more cities across the United States are becoming majority renters, which makes it even more important to understand what these new landlords imply for the housing stability of tenants. Housing instability encompasses multiple challenges, many of which are difficult to measure quantitatively. My thesis hopes to shed light on one factor contributing to the displacement of tenants: eviction filings. I find that in most property sizes, individual landlords are more likely to evict than corporate landlords are and that in-state corporates, specifically, evict at higher rates than out-of-state corporate landlords do. I also find that large investors, defined as those with more than 15 multi-family properties in Durham, are more likely to evict than small investors are. This research begins to shed a light on landlord characteristics related to eviction rates. However, there must be more investigation into other quantitative and qualitative factors contributing to housing instability in order to obtain a more complete picture for why tenants continue to be displaced. Similar analyses must be conducted in other cities to understand how the changing landscapes of ownership in the real-estate market will continue to impact the renters of this nation in the future.

