---
author: 'Ekim Buyuk'
date: 'May 2019'
institution: 'Duke University'
division: 'Trinity College of Arts and Sciences'
advisor: 'Colin Rundel'
altadvisor: 'Christopher Timmins'

committeememberone: 'Jim CLarke'
committeemembertwo: 'Amy Herring'
dus: 'Amy Herring'
department: 'Department of Statistical Science'
degree: 'Bachelor of Science in Statistical Science'
title: 'Landlords and Evictions: Changes in the Ownership of Multi-Family Rental Properties and Its Impact on Housing Stability in Durham, NC'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
#  thesisdowndss::thesis_pdf: default
  thesisdowndss::thesis_gitbook: default
#  thesisdowndss::thesis_word: default
#  thesisdowndss::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
acknowledgements: |
  I want to thank a few people.
dedication: |
  You can have a dedication here if you wish. 
preface: |
  This is an example of a thesis setup to use the reed thesis document class
  (for LaTeX) and the R bookdown package, in general.
bibliography: bib/thesis.bib
# Refer to your specific bibliography file in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
space_between_paragraphs: true
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdowndss package is
# installed and loaded. This thesisdowndss package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(thesisdowndss))
  devtools::install_github("mine-cetinkaya-rundel/thesisdowndss")
library(thesisdowndss)
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Abstract {-}

This thesis investigates the changes in the ownership of multi-family rental complexes in Durham between 2000 and 2018 and their subsequent impact on housing stability. Specifically, I model and compare the likelihood that an eviction filing is issued by corporate and individual landlords in the periods before and after a transaction. Since the early 2000s, institutional investor share in all property sizes has increased dramatically in the United States. In 2013, the Blackstone Group released the first-ever rated bond backed by single-family securitized rental payments, and since then, numerous firms have followed with similar security offerings, which as of 2018 include bonds backed by multi-family rental income. The surge of institutional investment in multi-family rental properties and its impacts on communities have remained largely ignored in academic literature. Durham County currently holds one of the highest eviction rates in North Carolina and ranks in the top 40 of highest evicting large cities in the United States. In my thesis, I uncover how ownership of rental properties in Durham has changed since the early 2000s and investigate whether the behaviors of "corporate landlords" differ significantly from those of individual investors (or “mom and pop” landlords”). I find that the proportion of properties under corporate ownership has increased across all property sizes since 2000, and the proportion of corporate owners that are based out-of-state has also increased. I also find evidence to suggest that different sizes of multi-family properties should be examined distinctly, as I uncover different trends across property sizes in both ownership and eviction rates. Using a fixed effects model, I find that overall, individuals appear to have a higher likelihood of filing an eviction against a tenant compared to institutional landlords in the months before and after a transaction. Finally, I find that large investors amongst both corporates and individuals, defined as investors that own more than 15 properties in Durham, are significantly more likely to evict than smaller investors are. 

*Keywords*: Housing stability, real-estate, multi-family rental market, institutional investor, corporate landlord

## Acknowledgements {-}

I would like to begin by thanking my professors, Professor Christopher Timmins, Professor Colin Rundel and Professor Grace Kim. Thank you to Professor Timmins for your support and guidance at all hours of the day, and for constantly challenging me to think critically about the questions I was asking and the methodology I was using. It was a pleasure working with you this year, and I learned so much from you. Thank you to Professor Rundel for your wisdom and patience. I did not realize that pursuing research was not only an academic pursuit but also a huge emotional undertaking, and your insight and calming presence was so critical in this process. Thank you for listening to every idea I had with an open-mind, and walking with me through the detailed processes necessary to get answers to each of these curiosities. Thank you also to Professor Grace Kim for your feedback and your constant support of my winding research path, as well as of my career throughout Duke. 
Thank you to John Killeen at DataWorks. Without your trust in me to pursue this research question with the care it deserves, this research would not have been possible. Thank you for all of the brainstorming sessions and hours spent investigating imperfect data problems. I learned so much through your mentorship. 
Thank you to the Durham Sherriff’s Department and Durham Tax Administration for letting me work with this data in my thesis. Finally, thank you to all of the friends who have kept me sane as I panicked about this research project: Anna-Karin Hess, David Pfeiffer, and Juan Philippe, I could not have done this without your support! 


## Dedication {-}

I would like to dedicate my thesis to my dad, who enjoys doing research as a fun hobby and inspired me to think that I might be the same. Guess this is one of the few ways that we are different, dad!
